---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: k8s-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
      - name: k8s-app
        image: etiennecoutaud/k8s-app:latest
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: k8s-challenge-data
